[package]
name = "rust-bf"
version = "0.0.1"
authors = ["Emualluig"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
